import type { Metadata } from 'next'
import Link from 'next/link'
import { Logo } from '@/components/ui/logo'

export const metadata: Metadata = {
  title: 'Terms of Service — Traka',
  description: 'Terms and conditions for using Traka, Nigeria\'s event and opportunity intelligence platform.',
}

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    content: 'By accessing or using Traka ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service. The Service is operated by Bluespectra Technologies Limited ("we", "us", or "our").',
  },
  {
    title: '2. Description of Service',
    content: 'Traka is an AI-powered platform that helps users discover professional events across Nigerian cities and global funding opportunities — including grants, scholarships, accelerators, incubators, and tenders — relevant to Nigerians. Event and opportunity data is generated by an AI model using live web search and is provided for informational purposes only.',
  },
  {
    title: '3. User Accounts',
    content: 'You must provide accurate, current, and complete information when creating an account. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. You must be at least 18 years old to use the Service. We reserve the right to suspend or terminate accounts that violate these Terms.',
  },
  {
    title: '4. Free Trial',
    content: `New users receive a 7-day free trial that includes 2 AI searches. No credit card is required to start the trial. At the end of the trial period, access to search features will be suspended unless you subscribe to a paid plan. Trial searches are consumed when a live AI search is performed; cached results from a previous search do not consume a search.`,
  },
  {
    title: '5. Subscriptions & Payments',
    content: 'Paid plans are offered on fixed-term basis (3, 6, or 12 months) and are processed securely by Paystack in Nigerian Naira (NGN). Subscriptions do not auto-renew — you must manually renew your plan before or after it expires. All payments are non-refundable except where required by applicable law. Prices are subject to change with reasonable notice.',
  },
  {
    title: '6. AI-Generated Content',
    content: 'Event listings and opportunity details are generated by an AI language model and may not always be accurate, complete, or up to date. We do not guarantee the accuracy of event dates, costs, venues, eligibility criteria, deadlines, or any other details. You should independently verify all information before making decisions, commitments, or payments based on content found on Traka. We accept no liability for losses arising from inaccurate or outdated AI-generated content.',
  },
  {
    title: '7. Acceptable Use',
    content: 'You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to scrape, reverse-engineer, or systematically extract data from the Service; (c) share or sell access to your account; (d) use automated tools or bots to interact with the Service; (e) interfere with the Service\'s operation, security, or infrastructure; or (f) upload or transmit malicious code or content.',
  },
  {
    title: '8. Intellectual Property',
    content: 'All content, branding, trademarks, and code comprising the Service are owned by or licensed to Bluespectra Technologies Limited. You are granted a limited, non-exclusive, non-transferable right to use the Service for its intended purpose. You may not reproduce, distribute, modify, or create derivative works without prior written permission.',
  },
  {
    title: '9. Disclaimers',
    content: 'The Service is provided "as is" and "as available" without warranties of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or secure, or that any particular event or opportunity will be available, accurate, or suitable for your needs.',
  },
  {
    title: '10. Limitation of Liability',
    content: 'To the maximum extent permitted by applicable law, Bluespectra Technologies Limited and its officers, employees, and affiliates shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of or inability to use the Service. Our total aggregate liability for any claim arising out of or related to these Terms shall not exceed the total amount you paid for the Service in the three months preceding the claim.',
  },
  {
    title: '11. Modifications to Terms',
    content: 'We may update these Terms from time to time. We will notify you of material changes by email or via a notice within the Service at least 14 days before they take effect. Continued use of the Service after updated Terms are posted constitutes your acceptance of those changes.',
  },
  {
    title: '12. Termination',
    content: 'You may close your account at any time by contacting us at hello@usetraka.com. We may suspend or terminate your account immediately if you breach these Terms or if required by law. Upon termination, your right to use the Service ceases and your data may be deleted in accordance with our Privacy Policy.',
  },
  {
    title: '13. Governing Law',
    content: 'These Terms are governed by and construed in accordance with the laws of the Federal Republic of Nigeria. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of Lagos State, Nigeria.',
  },
  {
    title: '14. Contact',
    content: 'If you have questions or concerns about these Terms, please contact us at hello@usetraka.com.',
  },
]

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--text)' }}>

      {/* Nav */}
      <nav style={{
        position: 'sticky', top: 0, zIndex: 50,
        borderBottom: '1px solid var(--border)',
        background: 'var(--nav-bg)',
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
      }}>
        <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 1.5rem', height: '60px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link href="/" style={{ textDecoration: 'none' }}>
            <Logo size="md" />
          </Link>
          <Link href="/" style={{ fontSize: '0.875rem', color: 'var(--text-muted)', textDecoration: 'none' }}>
            ← Back to home
          </Link>
        </div>
      </nav>

      <main style={{ maxWidth: '720px', margin: '0 auto', padding: '4rem 1.5rem 6rem' }}>

        {/* Header */}
        <div style={{ marginBottom: '3rem' }}>
          <p style={{ fontSize: '0.75rem', fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--accent)', marginBottom: '0.75rem' }}>
            Legal
          </p>
          <h1 style={{ fontSize: 'clamp(1.75rem, 4vw, 2.5rem)', fontWeight: 900, letterSpacing: '-0.03em', margin: '0 0 0.75rem', lineHeight: 1.1 }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)', margin: 0 }}>
            Last updated: June 2026
          </p>
        </div>

        {/* Intro */}
        <div style={{
          background: 'var(--surface)',
          border: '1px solid var(--border)',
          borderRadius: '12px',
          padding: '1.25rem 1.5rem',
          marginBottom: '3rem',
        }}>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: 1.75, margin: 0 }}>
            Please read these Terms carefully before using Traka. By creating an account or using the platform, you accept these Terms in full.
          </p>
        </div>

        {/* Sections */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '2.5rem' }}>
          {SECTIONS.map((s) => (
            <section key={s.title}>
              <h2 style={{
                fontSize: '0.9375rem', fontWeight: 700,
                margin: '0 0 0.625rem',
                color: 'var(--text)',
                letterSpacing: '-0.01em',
              }}>
                {s.title}
              </h2>
              <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: 1.8, margin: 0 }}>
                {s.content}
              </p>
            </section>
          ))}
        </div>

        {/* Footer CTA */}
        <div style={{
          marginTop: '4rem',
          paddingTop: '2rem',
          borderTop: '1px solid var(--border)',
          display: 'flex',
          flexDirection: 'column',
          gap: '0.75rem',
        }}>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)', margin: 0 }}>
            Questions about these Terms?{' '}
            <a href="mailto:hello@usetraka.com" style={{ color: 'var(--accent)', textDecoration: 'none' }}>
              hello@usetraka.com
            </a>
          </p>
          <div style={{ display: 'flex', gap: '1.25rem' }}>
            <Link href="/privacy" style={{ fontSize: '0.875rem', color: 'var(--accent)', textDecoration: 'none' }}>
              Privacy Policy →
            </Link>
            <Link href="/signup" style={{ fontSize: '0.875rem', color: 'var(--text-muted)', textDecoration: 'none' }}>
              Sign up
            </Link>
          </div>
        </div>

      </main>
    </div>
  )
}
